//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DB_
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConversationParticipant
    {
        public int ParticipantID { get; set; }
        public Nullable<int> ConversationID { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime JoinedDate { get; set; }
    
        public virtual Conversation Conversation { get; set; }
        public virtual User User { get; set; }
    }
}
