//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DB_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message()
        {
            this.Attachments = new HashSet<Attachment>();
        }
    
        public int MessageID { get; set; }
        public Nullable<int> SenderID { get; set; }
        public Nullable<int> ConversationID { get; set; }
        public string MessageText { get; set; }
        public System.DateTime SentDate { get; set; }
        public byte[] FileContent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual Conversation Conversation { get; set; }
        public virtual User User { get; set; }
    }
}
