//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DB_
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskCategoryMap
    {
        public int MapID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual TaskCategory TaskCategory { get; set; }
        public virtual Task Task { get; set; }
    }
}
