//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DB_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.TaskCategoryMaps = new HashSet<TaskCategoryMap>();
        }
    
        public int TaskID { get; set; }
        public Nullable<int> AssignedToID { get; set; }
        public Nullable<int> AssignedByID { get; set; }
        public string TaskDescription { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskCategoryMap> TaskCategoryMaps { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
